apiVersion: backstage.io/v1alpha1
kind: API

metadata:
  name: payment-api
  description: Payment REST API

spec:
  type: openapi
  lifecycle: production
  owner: group:default/team-payments

  definition: |
    openapi: 3.0.0
    info:
      title: Payment API
      version: 1.0.0
